docker run -itd \
  --name ecowitt2mqtt \
  --net=host \
  -e ECOWITT2MQTT_MQTT_BROKER=$MQTT_HOSTNAME \
  -e ECOWITT2MQTT_MQTT_USERNAME=$YOUR_MQTT_USERNAME \
  -e ECOWITT2MQTT_MQTT_PASSWORD=$YOUR_MQTT_PASSWORD \
  -e ECOWITT2MQTT_HASS_DISCOVERY=true \
  -e ECOWITT2MQTT_INPUT_DATA_FORMAT=ambient_weather \
  -e ECOWITT2MQTT_PORT=8080 \
  bachya/ecowitt2mqtt:latest

