version: '3.8'
services:
  vectordb:
    image: epsilla/vectordb:latest
    ports:
      - "8888:8888"
    environment:
      VECTOR_DB_PASSWORD: "pw"
    volumes:
      - vectordb_data:/var/lib/vectordb

volumes:
  vectordb_data:
