services:
    mariadb:
        image: mariadb:latest 
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=first_db
        volumes:
            - ./config/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ~/.evc/mariadb_test:/var/lib/mysql # maridadb data
        networks:
            - dev_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_HOST=mariadb
            - PMA_PORT=3306
        restart: always
        ports:
            - 8080:80 
        volumes:
            - /sessions
        networks:
            - dev_network

networks:
    dev_network:
        driver: bridge
