# JPark @ KETI, 2024
services:
    web:
        image: nginx
        ports:
            - 81:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./web:/var/www/html