version: '3.4'

# 사용법

# 1. 레디스 서버 docker-compose 코드를 다운로드 받습니다.
#    git clone git@github.com:againeureka/redis_server
#    cd redis_server
#
# 2. 홈 위치에 .evc 폴더를 만듭니다. 
#    mkdir ~/.evc
#
# 3. 레디스 서버를 실행합니다.
#    docker-compose up

# KETI, 2023
services:
    redis:
        image: redislabs/redisai
        container_name: redisai
        #environment:
        #    - REDIS_PASSWORD=
        #command: redis-server --requirepass $REDIS_PASSWORD
        ports:
            - 6379:6379
        volumes:
            - ~/.evc/redis/data:/data
        restart: always
        networks:
            - dev_network
        env_file:
            - .env

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            #- REDIS_PASSWORD=$REDIS_PASSWORD
            - HTTP_USER=temp
            - HTTP_PASSWORD=temp
        ports:
            - 8091:8081
        networks:
            - dev_network
        env_file:
            - .env

networks:
    dev_network:
        driver: bridge
