---
- name: Setup Raspberry Pi Edge Device
  hosts: all
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Ensure the edge service is running
      systemd:
        name: edge-service
        state: started
        enabled: yes